### ISSUE TITLE
How to run sync operations then concurrent operations in a queue?

### ISSUE THREAD

**Issue by Kalzem** [FabrizioBrancati/Queuer#14]
I have to run task A, B, C and D.
Task B needs A.
Tasks C and D need B.

I would like to run a queue in this order

1. Task A
2. Task B (needs A)
3. Task C and D in parallel (both need B)

What would be the easiest way to achieve it with Queuer?

**Comment by FabrizioBrancati** [comment]
You can do it like that:

```swift
let queue = Queuer(name: "MyCustomQueue")

let concurrentOperationA = ConcurrentOperation { _ in
    /// Your task here
}
let concurrentOperationB = ConcurrentOperation { _ in
    /// Your task here
}
let concurrentOperationC = ConcurrentOperation { _ in
    /// Your task here
}
let concurrentOperationD = ConcurrentOperation { _ in
    /// Your task here
}

queue.addChainedOperations([concurrentOperationA, concurrentOperationB]) {
    /// Your completion task here
}
queue.addChainedOperations([concurrentOperationB, concurrentOperationC]) {
    /// Your completion task here
}
queue.addChainedOperations([concurrentOperationB, concurrentOperationD]) {
    /// Your completion task here
}

/// Add this if you want to have a queue completion handler
queue.addCompletionHandler {
    /// Your completion task here
}
```

Let me know if this works 😄

**Comment by BabyAzerty** [comment]
Obviously this solution doesn't fit Queuer perfectly as there is no handling of retry etc, but maybe @FabrizioBrancati you can improve the lib with such feature? I would gladly help if I can.

**Comment by FabrizioBrancati** [comment]
I would really like to improve the `addChainedOperations(_:)` API!
Your idea sounds great, we need to understand how to achieve that.

Currently, the B task is executed 3 times, because of [this line](https://github.com/FabrizioBrancati/Queuer/blob/master/Sources/Queuer/Queuer.swift#L154)...

Maybe a solution can be to add an `addChainedOperations(_:)` to **ConcurrentOperation** class without that line.

I will be very happy to see a PR about that! Please don't hesitate on doing it!

**Comment by FabrizioBrancati** [comment]
Have you already started working on that? 😄

**Comment by FabrizioBrancati** [comment]
I'm closing this issue, because this PR has been merged and is now available on the develop branch 🎉
