### ISSUE TITLE
Is this the expected output?

### ISSUE THREAD

**Issue by josephbeuysmum** [FabrizioBrancati/Queuer#3]
For the following code, is the output after that the expected result, please?

```
class ViewController: UIViewController {
	var i:Int = 0
	override func viewDidLoad () {
		super.viewDidLoad()
		let queue = Queuer( name: "mike" )
		print( "a \(i)" )
		queue.addChainedOperations( [
			ConcurrentOperation{ self.i = 7 },
			ConcurrentOperation{ self.i = 5 },
			ConcurrentOperation{ self.i = 3 } ]
		) { print( "complete" ) }
		print( "b \(i)" )
		print( "hey 1" )
		print( "hey 2" )
		print( "hey 3" )
	}
}

a 0
b 3
complete
hey 1
hey 2
hey 3
```

**Comment by FabrizioBrancati** [comment]
Yes it’s correct, you have created 3 `ConcurrentOperation`s that may finish in 3 different times.
That’s why your code prints `completed` after `b 3`, but you can’t relys on that, it may be printed even after `hey 1`, `hey 2` or `hey 3`.
That’s why I have added a `completionHandler`, inside this handler you can be sure that every task has been completed.
Also, by creating 3 `ConcurrentOperation`s with the default value for `maxConcurrentOpertionCount` (`Int.max`) you can’t be sure that the final value is `3`, because the execution order may be different from the defined one.
